[[language]]
auto-format = true
name = "nix"

[language.formatter]
command = "alejandra"

[[language]]
auto-format = true
name = "toml"

[[language]]
name = "rust"

[language.auto-pairs]
"\"" = "\""
"(" = ")"
"<" = ">"
"[" = "]"
"`" = "`"
"{" = "}"
